// Family cookbook seed data.
window.RECIPES = [
  {
    id: "prime-rib",
    title: "Standing Prime Rib Roast",
    subtitle: "The 500° method. Set a timer, walk away — dinner is at 6.",
    author: "Patricia",
    cuisine: "American",
    course: "Dinner",
    diet: ["Gluten-free", "High protein", "Low carb", "Carnivore"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=1200&q=80",
    photoTone: "#5a1818",
    favorite: true,
    rating: 4.9,
    cookCount: 12,
    // SPECIAL: scales by WEIGHT. Cook time = 5 min/lb at 500°F, then off-oven rest.
    scaleBy: "weight",
    weightDefault: 5.5,
    weightUnit: "lb",
    servingsDefault: 8,        // ~0.7 lb per person
    cookMinsPerLb: 5.09,       // 28 min for 5.5 lb
    prep: 15, cook: 28, total: 28 + 120 + 17 + 15,
    difficulty: "Easy",
    nutrition: { cal: 720, protein: 58, carbs: 0, fat: 54, fiber: 0, sodium: 620 },
    ingredients: [
      { qty: 5.5,  unit: "lb",   item: "standing prime rib roast, bone-in", grp: "Main", scalesWithWeight: true, perLb: 1 },
      { qty: 2,    unit: "tbsp", item: "kosher salt", grp: "Rub", scalesWithWeight: true, perLb: 0.36 },
      { qty: 1,    unit: "tbsp", item: "coarse black pepper", grp: "Rub", scalesWithWeight: true, perLb: 0.18 },
      { qty: 2,    unit: "tsp",  item: "garlic powder", grp: "Rub", scalesWithWeight: true, perLb: 0.36 },
      { qty: 2,    unit: "tbsp", item: "fresh rosemary + thyme, chopped", grp: "Rub", scalesWithWeight: true, perLb: 0.36 },
      { qty: 4,    unit: "tbsp", item: "softened butter (optional herb-butter slather)", grp: "Rub", scalesWithWeight: true, perLb: 0.73 },
      { qty: 0,    unit: "",     item: "Horseradish cream or au jus, to serve", grp: "Serve" },
    ],
    steps: [
      { t: "Take roast out of fridge", d: "Sit on the counter uncovered (or loosely tented with parchment). 2½ hours minimum — even cooking depends on it.",                mins: 0,   precision: "easy",    label: "rest-pre" },
      { t: "Preheat oven",             d: "500°F. Rack in the lower-middle position.",                                                                                       mins: 15,  precision: "easy" },
      { t: "Season the roast",         d: "Pat dry. Rub with the salt-pepper-garlic-herb mix all over. Optional herb butter slather.",                                       mins: 10,  precision: "medium" },
      { t: "Roast at 500°F",           d: "Uncovered, fat-cap up. Timer for {COOKMINS} minutes.",                                                                            mins: 28,  precision: "watch",   dynamic: "cook" },
      { t: "Turn oven OFF",            d: "Do NOT open the door. The residual heat finishes the roast. 2 hr = medium-rare (130–135°F). 2¼ hr = medium (135–140°F).",          mins: 120, precision: "patient" },
      { t: "Pull and check",           d: "Check internal temp. 130°F for medium-rare. The crust will be deep mahogany.",                                                    mins: 2,   precision: "careful" },
      { t: "Rest",                     d: "Tent loosely with foil. 15 minutes — non-negotiable.",                                                                            mins: 17,  precision: "easy" },
      { t: "Slice and serve",          d: "Carve along the bones, then slice across the grain. Horseradish cream or au jus alongside.",                                      mins: 10,  precision: "medium" },
    ],
    tips: [
      "Cook time scales at ~5 minutes per pound at 500°F. The 'off oven' rest stays at 2 hours regardless.",
      "Pull the roast from the fridge 2½ hours before searing. Cold-center beef cooks unevenly.",
      "Do not open the oven during the off-oven phase. You will undo the entire method.",
    ],
    comments: [
      { name: "Mom", date: "Dec 25", text: "Did this Christmas for 14 people with an 8 lb roast — 41 minutes hot, 2 hours off. Perfect edge to edge." },
      { name: "Pete", date: "Nov 12", text: "Saved $40 buying the whole rib and tying it myself. Same result." },
    ],
  },

  {
    id: "linguine-vongole",
    title: "Linguine alle Vongole",
    subtitle: "Pantry-friendly. White wine, garlic, clams — done in 15 minutes.",
    author: "Patricia",
    cuisine: "Italian",
    course: "Dinner",
    diet: ["Dairy-free option", "Pescatarian", "High protein"],
    occasion: "Date night",
    photo: "https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=1200&q=80",
    photoTone: "#3a5a3a",
    favorite: true,
    rating: 4.8,
    cookCount: 26,
    servingsDefault: 4,
    prep: 5, cook: 15, total: 20,
    difficulty: "Easy",
    nutrition: { cal: 540, protein: 22, carbs: 64, fat: 19, fiber: 3, sodium: 720 },
    ingredients: [
      { qty: 1,    unit: "pkg",   item: "linguini (about 1 lb)", grp: "Pasta" },
      { qty: 0.25, unit: "cup",   item: "olive oil (plus more to finish)", grp: "Pasta" },
      { qty: 2,    unit: "tbsp",  item: "unsalted butter", grp: "Pasta" },
      { qty: 2,    unit: "tbsp",  item: "pre-minced garlic (or 3–6 fresh cloves, minced)", grp: "Pasta" },
      { qty: 1,    unit: "tbsp",  item: "red pepper flakes", grp: "Pasta" },
      { qty: 8,    unit: "oz",    item: "clam juice (1 bottle)", grp: "Clams" },
      { qty: 2,    unit: "cans",  item: "minced/chopped clams, with juice", grp: "Clams" },
      { qty: 0.5,  unit: "cup",   item: "white wine (Chardonnay or Pinot Grigio)", grp: "Clams" },
      { qty: 0.5,  unit: "",      item: "lemon, zested (optional)", grp: "Finish" },
      { qty: 3,    unit: "tbsp",  item: "Parmesan, finely grated (optional)", grp: "Finish" },
      { qty: 1,    unit: "bunch", item: "fresh parsley, chopped", grp: "Finish" },
      { qty: 0,    unit: "",      item: "salt and pepper, to taste", grp: "Finish" },
    ],
    steps: [
      { t: "Boil the pasta",      d: "Heavily salted water — like the sea. Cook linguini just shy of al dente. Reserve a cup of pasta water before draining.", mins: 9, precision: "medium" },
      { t: "Bloom the aromatics", d: "Olive oil in a large pan, medium. Garlic + red pepper flakes — cook 1–2 minutes until fragrant. Don't brown the garlic.", mins: 2, precision: "watch" },
      { t: "Wine + clam juice",   d: "Add clam juice and white wine. Simmer 2–3 minutes to take the alcohol edge off.",                                          mins: 3, precision: "easy" },
      { t: "Add the clams",       d: "Stir in canned clams with their juice. Simmer another 2–3 minutes.",                                                       mins: 3, precision: "easy" },
      { t: "Season",              d: "Lemon zest (if using), salt, plenty of black pepper.",                                                                     mins: 1, precision: "easy" },
      { t: "Toss",                d: "Drained pasta into the sauce with a splash of pasta water. Toss vigorously until glossy.",                                 mins: 2, precision: "medium" },
      { t: "Finish off heat",     d: "Off the heat: butter and Parm. Stir to emulsify. Parsley on top. Serve immediately.",                                      mins: 1, precision: "careful" },
    ],
    tips: [
      "Replace 1 can with fresh vongole clams if you can find them — steam them open in the sauce.",
      "Want a thicker sauce? Whisk 1 tbsp of flour into the wine before adding.",
      "Reserved pasta water is the secret. Add it a splash at a time until the sauce coats the strands.",
    ],
    comments: [
      { name: "Jules", date: "May 14", text: "Date-night go-to. Open the second bottle of wine when the first one hits the pan." },
    ],
  },

  {
    id: "blueberry-lemon-rolls",
    title: "Blueberry Lemon Pie Rolls",
    subtitle: "Cinnamon roll meets blueberry pie. Lemon glaze on top.",
    author: "Patricia",
    cuisine: "American",
    course: "Breakfast",
    diet: ["Vegetarian"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=1200&q=80",
    photoTone: "#5a3a7a",
    favorite: false,
    rating: 4.7,
    cookCount: 7,
    servingsDefault: 9,
    prep: 30, cook: 30, total: 60 + 60, // includes rise
    difficulty: "Medium",
    nutrition: { cal: 380, protein: 6, carbs: 62, fat: 12, fiber: 2, sodium: 280 },
    ingredients: [
      { qty: 3.25, unit: "cups", item: "all-purpose flour", grp: "Dough" },
      { qty: 0.25, unit: "cup",  item: "sugar", grp: "Dough" },
      { qty: 2.25, unit: "tsp",  item: "instant yeast (1 packet)", grp: "Dough" },
      { qty: 0.75, unit: "tsp",  item: "kosher salt", grp: "Dough" },
      { qty: 0.75, unit: "cup",  item: "warm whole milk", grp: "Dough" },
      { qty: 4,    unit: "tbsp", item: "butter, melted and slightly cooled", grp: "Dough" },
      { qty: 1,    unit: "",     item: "large egg", grp: "Dough" },
      { qty: 1,    unit: "tsp",  item: "vanilla", grp: "Dough" },
      { qty: 2,    unit: "cups", item: "blueberries (fresh or frozen, don't thaw)", grp: "Filling" },
      { qty: 0.33, unit: "cup",  item: "sugar", grp: "Filling" },
      { qty: 2,    unit: "tbsp", item: "cornstarch", grp: "Filling" },
      { qty: 1,    unit: "",     item: "lemon, zested and juiced", grp: "Filling" },
      { qty: 1,    unit: "cup",  item: "powdered sugar", grp: "Glaze" },
      { qty: 2,    unit: "tbsp", item: "lemon juice", grp: "Glaze" },
      { qty: 1,    unit: "tsp",  item: "lemon zest", grp: "Glaze" },
    ],
    steps: [
      { t: "Activate the yeast",  d: "Warm milk (105°F) + sugar + yeast. Sit 5 minutes until foamy.", mins: 5, precision: "medium" },
      { t: "Mix the dough",       d: "Add melted butter, egg, vanilla. Stir in flour + salt until shaggy. Knead 6–8 minutes until smooth and elastic.", mins: 12, precision: "medium" },
      { t: "First rise",          d: "Oiled bowl, covered. Warm spot. 1 hour, until doubled.", mins: 60, precision: "easy", hands: 0 },
      { t: "Make the filling",    d: "Toss blueberries with sugar, cornstarch, lemon zest, lemon juice. Don't pre-cook — they jam inside the rolls.", mins: 3, precision: "easy" },
      { t: "Roll and fill",       d: "Punch down. Roll dough into a 12×16 rectangle. Spread blueberry filling, leaving a 1\" border.", mins: 8, precision: "careful" },
      { t: "Roll and slice",      d: "Roll up tightly from the long side. Slice with unflavored dental floss into 9 rolls. Floss beats a knife — no smushing.", mins: 5, precision: "careful" },
      { t: "Second rise",         d: "Rolls in a buttered 9×13. Cover. 30–40 minutes until puffy and touching.", mins: 35, precision: "easy", hands: 0 },
      { t: "Bake",                d: "375°F until tops are deeply golden and the centers are set.", mins: 28, precision: "watch" },
      { t: "Glaze warm",          d: "Whisk powdered sugar + lemon juice + zest. Pour over rolls while still warm. Eat one before anyone notices.", mins: 4, precision: "easy" },
    ],
    tips: [
      "Frozen blueberries: do not thaw. They bleed less, and the cold helps the dough hold its shape during slicing.",
      "Make-ahead: shape the rolls, cover, and refrigerate overnight after step 6. Let them warm up 30 min before baking.",
      "Want them extra rich? Brush the rolled dough with 2 tbsp soft butter before adding the filling.",
    ],
    comments: [
      { name: "Sam", date: "Jul 4", text: "Brought to brunch — gone in 4 minutes. The dental floss trick is real." },
      { name: "Em",  date: "Jun 20", text: "Did half blueberry, half raspberry. Worth it." },
    ],
  },

  {
    id: "polish-vegetable-salad",
    title: "Polish Vegetable Salad (Sałatka Jarzynowa)",
    subtitle: "Creamy, nostalgic, and made for family gatherings — somehow always disappears faster than expected.",
    author: "Ryszard",
    cuisine: "Polish",
    course: "Appetizer",
    diet: ["Vegetarian"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=80",
    photoTone: "#7a8a4a",
    favorite: false,
    rating: 4.8,
    cookCount: 3,
    servingsDefault: 7,
    prep: 30, cook: 25, total: 175, // includes 2 hr chill
    difficulty: "Easy",
    nutrition: { cal: 290, protein: 6, carbs: 24, fat: 19, fiber: 4, sodium: 540 },
    ingredients: [
      { qty: 3,    unit: "",     item: "carrots", grp: "Vegetables" },
      { qty: 0.5,  unit: "",     item: "celery root", grp: "Vegetables" },
      { qty: 1,    unit: "",     item: "parsley root", grp: "Vegetables" },
      { qty: 2,    unit: "",     item: "potatoes", grp: "Vegetables" },
      { qty: 2,    unit: "",     item: "apples (or 1 large)", grp: "Mix-Ins" },
      { qty: 2,    unit: "",     item: "hard-boiled eggs", grp: "Mix-Ins" },
      { qty: 0.5,  unit: "",     item: "onion, finely chopped", grp: "Mix-Ins" },
      { qty: 3,    unit: "",     item: "dill pickles", grp: "Mix-Ins" },
      { qty: 0.5,  unit: "can",  item: "green peas, drained", grp: "Mix-Ins" },
      { qty: 2,    unit: "tbsp", item: "sour cream", grp: "Dressing" },
      { qty: 0,    unit: "",     item: "mayonnaise, to taste", grp: "Dressing" },
      { qty: 1,    unit: "tbsp", item: "mustard", grp: "Dressing" },
      { qty: 0,    unit: "",     item: "salt and pepper, to taste", grp: "Dressing" },
      { qty: 0,    unit: "",     item: "fresh parsley, for garnish", grp: "Finish" },
    ],
    steps: [
      { t: "Cook the vegetables",       d: "Wash the carrots, potatoes, celery root, and parsley root. Boil in salted water or vegetable stock until fork tender but not falling apart.", mins: 25,  precision: "medium" },
      { t: "Boil the eggs",             d: "In a separate pot, boil the eggs until hard-boiled. Cool completely before peeling.",                                                          mins: 10,  precision: "easy" },
      { t: "Cool everything completely", d: "Drain the vegetables and allow them to cool fully before chopping. This keeps the salad from becoming watery.",                                mins: 20,  precision: "careful" },
      { t: "Chop the ingredients",      d: "Dice the cooked vegetables, apples, eggs, pickles, and onion into small, even pieces. Add to a large mixing bowl. (Can be done a day ahead.)",  mins: 15,  precision: "medium" },
      { t: "Mix the salad",             d: "Add the green peas, sour cream, mustard, mayo, salt, and pepper. Stir gently until evenly combined. Start lighter on the mayo and mustard — you can always add more later.", mins: 5, precision: "easy" },
      { t: "Chill before serving",      d: "Cover and refrigerate at least 2 hours so the flavors come together. Before serving, mix again and adjust seasoning, mustard, or mayo if needed.", mins: 120, precision: "patient", hands: 0 },
    ],
    tips: [
      "Dice everything small and evenly for the best texture.",
      "Vegetable stock adds more flavor than plain salted water.",
      "If the salad feels dry after chilling, stir in another spoonful of mayo before serving.",
      "Dill pickles are key — they balance the richness and add brightness.",
      "This is a 'measure with your heart' recipe — every Polish family makes it slightly differently. Some add corn, ham, or extra egg; this version keeps it traditional.",
    ],
    comments: [],
  },

  {
    id: "ryszards-tomato-soup",
    title: "Ryszard's Tomato Soup",
    subtitle: "Simple, comforting, deeply nostalgic — the longer it simmers, the better it gets.",
    author: "Ryszard",
    cuisine: "Polish",
    course: "Dinner",
    diet: ["High protein"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200&q=80",
    photoTone: "#a83a1a",
    favorite: false,
    rating: 4.9,
    cookCount: 5,
    servingsDefault: 7,
    prep: 15, cook: 75, total: 90,
    difficulty: "Easy",
    nutrition: { cal: 240, protein: 16, carbs: 11, fat: 14, fiber: 2, sodium: 780 },
    ingredients: [
      { qty: 1,    unit: "lb",   item: "chicken pieces", grp: "Soup Base" },
      { qty: 0.5,  unit: "lb",   item: "pork ribs", grp: "Soup Base" },
      { qty: 1,    unit: "",     item: "onion, peeled", grp: "Soup Base" },
      { qty: 1,    unit: "",     item: "carrot, peeled (optional, for sweetness)", grp: "Soup Base" },
      { qty: 2,    unit: "",     item: "garlic cloves", grp: "Soup Base" },
      { qty: 0.5,  unit: "tbsp", item: "Vegeta seasoning", grp: "Soup Base" },
      { qty: 0,    unit: "",     item: "salt and pepper, to taste", grp: "Soup Base" },
      { qty: 8,    unit: "cups", item: "water", grp: "Soup Base" },
      { qty: 1,    unit: "can",  item: "crushed tomatoes (large)", grp: "Tomato" },
      { qty: 2,    unit: "tbsp", item: "sour cream", grp: "Finish" },
      { qty: 1,    unit: "tbsp", item: "flour", grp: "Finish" },
      { qty: 0,    unit: "",     item: "warm water, for mixing", grp: "Finish" },
    ],
    steps: [
      { t: "Build the broth",       d: "Add the chicken, ribs, onion, carrot (if using), garlic, Vegeta, salt, pepper, and water to a large pot. Bring to a boil, then reduce to a gentle simmer.", mins: 60, precision: "medium" },
      { t: "Remove the onion",      d: "Once the broth is flavorful and the meat is tender, remove the onion and skim any foam or excess fat from the top if desired.",                              mins: 5,  precision: "easy" },
      { t: "Add the tomatoes",      d: "Pour in the crushed tomatoes and stir well. Simmer another 15–20 minutes so the flavors combine. (Crushed beats diced — smoother, no skin pieces.)",         mins: 20, precision: "easy" },
      { t: "Make the cream mixture", d: "In a small bowl, whisk the sour cream, flour, and a few spoonfuls of warm water until completely smooth. To prevent curdling, slowly stir a ladle of warm soup broth into the mixture first.", mins: 3, precision: "careful" },
      { t: "Finish the soup",       d: "Slowly stir the cream mixture into the soup. Simmer gently for a few minutes until slightly thickened. Taste and adjust salt and pepper before serving.",   mins: 5,  precision: "easy" },
    ],
    tips: [
      "The carrot softens the acidity and adds natural sweetness.",
      "Do not boil aggressively after adding the sour cream mixture — it will curdle.",
      "Tastes even better the next day after the flavors settle.",
      "Serve with fresh bread, buttered rolls, or noodles.",
      "If the soup tastes too acidic, add a pinch of sugar. Some families blend it smooth; others leave it rustic.",
    ],
    comments: [],
  },

  {
    id: "trish-covid-bread",
    title: "Trish's \"Covid Bread\"",
    subtitle: "No-knead loaf adapted from Mark Bittman — crackly crust, chewy inside, almost impossible to mess up.",
    author: "Patricia",
    cuisine: "American",
    course: "Breakfast",
    diet: ["Vegan", "Dairy-free", "Nut-free"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&q=80",
    photoTone: "#8a5a2a",
    favorite: false,
    rating: 4.9,
    cookCount: 18,
    servingsDefault: 8,
    prep: 10, cook: 45, total: 60 + 15 * 60, // includes 15 hr rise (midpoint of 12–18)
    difficulty: "Easy",
    nutrition: { cal: 170, protein: 5, carbs: 34, fat: 1, fiber: 1, sodium: 290 },
    ingredients: [
      { qty: 3,    unit: "cups", item: "all-purpose or bread flour (430g)", grp: "Dough" },
      { qty: 0.25, unit: "tsp",  item: "instant yeast", grp: "Dough" },
      { qty: 1.25, unit: "tsp",  item: "salt", grp: "Dough" },
      { qty: 1.5,  unit: "cups", item: "water (350ml)", grp: "Dough" },
      { qty: 0,    unit: "",     item: "extra flour, as needed", grp: "For Dusting" },
      { qty: 0,    unit: "",     item: "cornmeal or wheat bran, for dusting (optional)", grp: "For Dusting" },
    ],
    steps: [
      { t: "Mix the dough",     d: "Combine the flour, yeast, and salt in a large bowl. Add the water and stir until a shaggy, sticky dough forms. It should look rough and messy — that's right.", mins: 5,   precision: "easy" },
      { t: "First rise",        d: "Cover the bowl tightly with plastic wrap, foil, or a towel. Leave at room temperature for 12–18 hours, until the surface is dotted with bubbles and the dough has doubled.", mins: 900, precision: "patient", hands: 0 },
      { t: "Shape the dough",   d: "Turn the dough onto a well-floured surface. Fold it over itself once or twice and shape gently into a loose ball. Cover loosely and let rest while the oven heats.", mins: 15,  precision: "easy" },
      { t: "Heat the pot",      d: "Place a Dutch oven with its lid into the oven and preheat to 450°F. Let the pot heat at least 30 minutes so it becomes very hot.", mins: 30,  precision: "careful" },
      { t: "Bake covered",      d: "Carefully remove the hot pot. Dust the bottom with cornmeal or bran if using, then place the dough inside. Cover with the lid and bake for 30 minutes.", mins: 30,  precision: "medium" },
      { t: "Bake uncovered",    d: "Remove the lid and continue baking another 10–15 minutes until deeply golden brown and crisp. The bread should sound hollow when tapped.", mins: 13,  precision: "watch" },
      { t: "Cool before slicing", d: "Transfer to a wire rack and let cool at least 30 minutes before cutting.", mins: 30,  precision: "patient" },
    ],
    tips: [
      "The wetter and stickier the dough, the better the texture.",
      "Bread flour gives more chew, but all-purpose works beautifully too.",
      "A longer rise (closer to 18 hours) creates deeper flavor and better bubbles.",
      "Don't skip preheating the Dutch oven — that's what creates the bakery-style crust.",
      "Best served warm with salted butter, soup, or olive oil. The dough looks wrong right up until it becomes amazing.",
    ],
    comments: [],
  },

  {
    id: "block-party-ribs",
    title: "Block Party Winning Ribs",
    subtitle: "The ribs that disappear first at every family BBQ. Simmer first, marinate overnight, finish on the grill.",
    author: "Grace",
    cuisine: "American",
    course: "Dinner",
    diet: ["Gluten-free", "Dairy-free", "High protein", "Carnivore"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&q=80",
    photoTone: "#5a2818",
    favorite: false,
    rating: 4.9,
    cookCount: 9,
    servingsDefault: 5,
    prep: 20, cook: 90, total: 20 + 60 + 12 * 60 + 38, // simmer + overnight + bake/grill
    difficulty: "Medium",
    nutrition: { cal: 620, protein: 36, carbs: 24, fat: 42, fiber: 1, sodium: 980 },
    ingredients: [
      { qty: 2,    unit: "racks", item: "baby back or spare ribs", grp: "Ribs" },
      { qty: 0,    unit: "",      item: "water, enough to cover", grp: "Ribs" },
      { qty: 2,    unit: "",      item: "bay leaves", grp: "Ribs" },
      { qty: 1,    unit: "",      item: "onion, chopped (optional)", grp: "Ribs" },
      { qty: 1,    unit: "tbsp",  item: "salt", grp: "Ribs" },
      { qty: 1,    unit: "tsp",   item: "black pepper", grp: "Ribs" },
      { qty: 1,    unit: "cup",   item: "ketchup", grp: "Marinade" },
      { qty: 2,    unit: "tbsp",  item: "brown sugar (optional)", grp: "Marinade" },
      { qty: 1,    unit: "tsp",   item: "smoked paprika", grp: "Marinade" },
      { qty: 1,    unit: "tsp",   item: "garlic powder", grp: "Marinade" },
      { qty: 1,    unit: "tsp",   item: "onion powder", grp: "Marinade" },
      { qty: 0.5,  unit: "tsp",   item: "black pepper", grp: "Marinade" },
      { qty: 0,    unit: "",      item: "Bullseye BBQ sauce (non-negotiable)", grp: "Finish" },
    ],
    steps: [
      { t: "Prep the ribs",          d: "Remove the thin membrane from the back of the ribs using a blunt butter knife and paper towel for grip. This helps the ribs become more tender and absorb flavor better.", mins: 10, precision: "medium" },
      { t: "Simmer until tender",    d: "Place the ribs in a large pot, cover with water. Add bay leaves, onion (if using), salt, pepper. Boil, then drop to a gentle simmer. Baby backs: 30–45 min. Spare ribs: 45–60 min. Tender but not falling apart.", mins: 55, precision: "medium" },
      { t: "Make the marinade",      d: "While the ribs cook, mix ketchup, brown sugar, smoked paprika, garlic powder, onion powder, and black pepper.", mins: 5, precision: "easy" },
      { t: "Coat and chill overnight", d: "Remove ribs from the pot, cool slightly, pat dry. Generously coat both sides with the ketchup marinade. Wrap tightly or place in a shallow dish and refrigerate overnight. This is what makes them block-party winning.", mins: 720, precision: "patient", hands: 0 },
      { t: "Bake or barbecue",       d: "Preheat oven or grill to 350°F. Brush the ribs generously with Bullseye BBQ sauce and cook 30–45 minutes, basting occasionally until sticky, caramelized, and heated through. For extra smoke, finish on the grill 10–15 min until lightly charred.", mins: 38, precision: "watch" },
      { t: "Rest and serve",         d: "Let the ribs rest a few minutes before slicing. Serve with extra BBQ sauce on the side.", mins: 5, precision: "easy" },
    ],
    tips: [
      "Bullseye BBQ sauce is considered non-negotiable in this family.",
      "Overnight marinating makes a huge difference — don't skip it.",
      "Finishing on the grill gives the sauce that sticky, smoky texture.",
      "The leftover rib broth is an incredible base for tomato soup — add onion if you plan to reuse it.",
      "Don't boil aggressively during the simmer; gentle heat keeps the meat tender instead of tough.",
    ],
    comments: [],
  },

  {
    id: "dygas-duck-dynasty",
    title: "Dygas Duck Dynasty",
    subtitle: "Slow-braised duck in a savory-fruity sauce with sour cherries, vermouth, and orange. Hover-around-the-stove kind of dish.",
    author: "Grace & Patricia",
    cuisine: "French",
    course: "Dinner",
    diet: ["Gluten-free", "Dairy-free", "High protein", "Low carb", "Carnivore"],
    occasion: "Date night",
    photo: "https://images.unsplash.com/photo-1432139509613-5c4255815697?w=1200&q=80",
    photoTone: "#4a1a2a",
    favorite: false,
    rating: 4.9,
    cookCount: 4,
    servingsDefault: 6,
    prep: 20, cook: 165, total: 200, // 20 prep + 15 sear + 2.5 hr braise midpoint
    difficulty: "Patient",
    nutrition: { cal: 540, protein: 38, carbs: 8, fat: 38, fiber: 1, sodium: 620 },
    ingredients: [
      { qty: 6,    unit: "",     item: "duck breasts", grp: "Duck" },
      { qty: 0,    unit: "",     item: "salt and pepper, to taste", grp: "Duck" },
      { qty: 1,    unit: "",     item: "large garlic clove, minced", grp: "Aromatics" },
      { qty: 1,    unit: "",     item: "white onion, sliced", grp: "Aromatics" },
      { qty: 2,    unit: "tbsp", item: "butter", grp: "Aromatics" },
      { qty: 2,    unit: "cups", item: "broth or prepared bouillon", grp: "Braising Liquid" },
      { qty: 2,    unit: "tbsp", item: "sour cherries in syrup", grp: "Braising Liquid" },
      { qty: 0,    unit: "",     item: "heavy splash of vermouth or white wine", grp: "Braising Liquid" },
      { qty: 0.5,  unit: "",     item: "fresh orange, juiced", grp: "Braising Liquid" },
    ],
    steps: [
      { t: "Score and season the duck", d: "Pat the duck breasts dry. Score the skin in a crosshatch pattern, being careful not to cut into the meat. Season generously with salt and pepper.", mins: 10,  precision: "medium" },
      { t: "Sear the duck",             d: "Melt butter in a large heavy-bottomed pan or Dutch oven over medium heat. Place the duck skin-side down and sear until deeply golden and crispy, about 4 minutes per side. Remove and set aside.", mins: 15, precision: "careful" },
      { t: "Build the flavor base",     d: "In the same pan, add the onion and cook until softened and lightly golden. Add the garlic and cook another minute until fragrant.", mins: 8, precision: "easy" },
      { t: "Braise low and slow",       d: "Return the duck breasts to the pan. Add broth, sour cherries with a little syrup, vermouth or wine, and orange juice. Lower the heat, cover, and simmer gently for 2–3 hours until tender. (Optional: slice the breasts before simmering to speed cooking and deepen flavor.)", mins: 150, precision: "patient", hands: 0 },
      { t: "Finish and serve",          d: "Taste the sauce and adjust seasoning. Serve warm with potatoes, bread, or buttered noodles to soak up the sauce.", mins: 5, precision: "easy" },
    ],
    tips: [
      "Sour cherries in syrup are the secret — subtle sweetness and richness that balance the duck.",
      "Vermouth adds depth without overpowering. White wine works too.",
      "Don't rush the sear — crispy browned skin builds the flavor foundation.",
      "The sauce becomes even richer the next day.",
      "Eat during a snowstorm with candles lit. People stop talking for the first few bites.",
    ],
    comments: [],
  },

  {
    id: "ewas-pierogies",
    title: "Ewa's Pierogies",
    subtitle: "Soft handmade pierogies — potato & cheese or sweet cabbage. Made assembly-line style around a crowded kitchen table.",
    author: "Ewa",
    cuisine: "Polish",
    course: "Dinner",
    diet: ["Vegetarian"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1601000938259-9e92002320b2?w=1200&q=80",
    photoTone: "#c89a5a",
    favorite: false,
    rating: 5.0,
    cookCount: 11,
    servingsDefault: 11,
    prep: 60, cook: 45, total: 165, // includes assembly
    difficulty: "Patient",
    nutrition: { cal: 380, protein: 14, carbs: 49, fat: 14, fiber: 4, sodium: 520 },
    ingredients: [
      { qty: 2,    unit: "cups", item: "water", grp: "Dough" },
      { qty: 0.25, unit: "cup",  item: "butter", grp: "Dough" },
      { qty: 6.5,  unit: "cups", item: "flour (about half a bag)", grp: "Dough" },
      { qty: 1,    unit: "tsp",  item: "salt", grp: "Dough" },
      { qty: 2,    unit: "kg",   item: "Russet potatoes", grp: "Potato & Cheese Filling" },
      { qty: 1,    unit: "kg",   item: "twaróg (farmer's cheese or strained cottage cheese)", grp: "Potato & Cheese Filling" },
      { qty: 2,    unit: "",     item: "yellow onions, diced", grp: "Potato & Cheese Filling" },
      { qty: 0.5,  unit: "container", item: "sour cream (small)", grp: "Potato & Cheese Filling" },
      { qty: 1,    unit: "tbsp", item: "butter", grp: "Potato & Cheese Filling" },
      { qty: 0,    unit: "",     item: "salt and pepper, generously to taste", grp: "Potato & Cheese Filling" },
      { qty: 1,    unit: "",     item: "green cabbage", grp: "Sweet Cabbage Filling" },
      { qty: 0.5,  unit: "kg",   item: "twaróg (farmer's cheese or strained cottage cheese)", grp: "Sweet Cabbage Filling" },
      { qty: 2,    unit: "",     item: "yellow onions, diced", grp: "Sweet Cabbage Filling" },
      { qty: 1,    unit: "tbsp", item: "butter", grp: "Sweet Cabbage Filling" },
      { qty: 0,    unit: "",     item: "salt and pepper, generously to taste", grp: "Sweet Cabbage Filling" },
    ],
    steps: [
      { t: "Make the filling first",   d: "Prepare either filling before making the dough so it has time to cool completely. Warm filling makes the dough harder to work with.", mins: 45, precision: "careful" },
      { t: "Potato: cook the potatoes", d: "Boil the potatoes until very soft. Drain thoroughly and mash until completely smooth.", mins: 25, precision: "easy" },
      { t: "Potato: cook the onions",  d: "Cook the onions slowly in butter over medium-low heat until soft and translucent. Do not brown them.", mins: 12, precision: "easy" },
      { t: "Potato: mix the filling",  d: "Crumble or finely grate the twaróg so there are no large chunks. Mix potatoes, cheese, onions, and sour cream until smooth and creamy — almost like a thick Boursin texture. Season generously with salt and pepper.", mins: 10, precision: "easy" },
      { t: "Cabbage: cook the cabbage", d: "Cut the cabbage into 2–3 large sections and boil until tender. Drain very well.", mins: 20, precision: "medium" },
      { t: "Cabbage: chop and mix",    d: "Finely chop the cooked cabbage until soft and delicate. Cook onions slowly in butter until translucent, then combine with cabbage and cheese. Season generously with salt and pepper.", mins: 15, precision: "easy" },
      { t: "Make the dough",           d: "Bring the water to a boil and pour into a large bowl. Add butter and salt, stirring until melted. Gradually add flour until the dough no longer sticks to the bowl or your fingers — soft and pliable, not dry. Knead until smooth.", mins: 18, precision: "medium" },
      { t: "Roll and cut",             d: "On a floured surface, roll the dough out very thin. Cut circles using the top of a drinking glass.", mins: 15, precision: "medium" },
      { t: "Fill and seal",            d: "Place filling into the center of each circle. Fold over and firmly seal the edges with a fork, or lightly wet the edges with water and press tightly closed. Proper sealing prevents them from opening while boiling.", mins: 38, precision: "patient" },
      { t: "Boil the pierogies",       d: "Boil in salted water until the pierogies float to the top and become pale and slightly puffed. Remove with a slotted spoon. Cook in batches — about 5 min per batch.", mins: 25, precision: "watch" },
      { t: "Serve or freeze",          d: "Serve immediately with butter and onions, or lay them in a single layer on a baking sheet and freeze. Once frozen, transfer to freezer bags.", mins: 10, precision: "easy" },
    ],
    tips: [
      "The dough should feel soft and silky, never stiff.",
      "Twaróg gives the filling its authentic flavor and texture — don't substitute regular cottage cheese without straining it first.",
      "A small amount of Boursin cheese is the secret ingredient for extra creaminess.",
      "Thin dough makes the best pierogies.",
      "Fried leftovers the next morning in butter are arguably even better than fresh.",
    ],
    comments: [],
  },

  {
    id: "kt-turkey",
    title: "K&T Turkey",
    subtitle: "The holiday centerpiece — bacon-draped, constantly basted, vegetables soaking up the drippings. Hovering-around-the-turkey energy.",
    author: "Kayla & Patricia",
    cuisine: "American",
    course: "Dinner",
    diet: ["Gluten-free option", "High protein", "Carnivore"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=1200&q=80",
    photoTone: "#8a3a18",
    favorite: false,
    rating: 5.0,
    cookCount: 6,
    servingsDefault: 13,
    prep: 45, cook: 240, total: 45 + 240 + 12 * 60, // 4 hr cook + overnight
    difficulty: "Patient",
    nutrition: { cal: 620, protein: 42, carbs: 24, fat: 38, fiber: 2, sodium: 890 },
    ingredients: [
      { qty: 1,    unit: "",     item: "whole turkey", grp: "Turkey" },
      { qty: 2,    unit: "",     item: "whole garlic bulbs", grp: "Turkey" },
      { qty: 0,    unit: "",     item: "olive oil", grp: "Turkey" },
      { qty: 0,    unit: "",     item: "salt and pepper", grp: "Turkey" },
      { qty: 0,    unit: "",     item: "Italian seasoning (thyme, rosemary, marjoram, oregano, basil, sage)", grp: "Seasonings" },
      { qty: 0,    unit: "",     item: "poultry seasoning", grp: "Seasonings" },
      { qty: 0,    unit: "",     item: "thick-cut bacon", grp: "Pan" },
      { qty: 0,    unit: "",     item: "potatoes", grp: "Pan" },
      { qty: 0,    unit: "",     item: "carrots", grp: "Pan" },
      { qty: 0,    unit: "",     item: "celery", grp: "Pan" },
      { qty: 0,    unit: "",     item: "turkey neck and giblets", grp: "Pan" },
      { qty: 0,    unit: "",     item: "water, for roasting pan", grp: "Pan" },
      { qty: 2,    unit: "boxes", item: "Kraft Stove Top stuffing", grp: "Stuffing" },
      { qty: 2,    unit: "lb",   item: "pork or pork/beef mix", grp: "Stuffing" },
      { qty: 6,    unit: "",     item: "garlic cloves, minced", grp: "Stuffing" },
      { qty: 2,    unit: "",     item: "medium onions, minced", grp: "Stuffing" },
      { qty: 0,    unit: "",     item: "Vegeta seasoning, generously to taste", grp: "Stuffing" },
      { qty: 0,    unit: "",     item: "black pepper", grp: "Stuffing" },
      { qty: 3,    unit: "",     item: "eggs (2–4)", grp: "Stuffing" },
      { qty: 0,    unit: "",     item: "basil", grp: "Stuffing" },
      { qty: 0,    unit: "",     item: "fresh or frozen cranberries", grp: "Stuffing" },
      { qty: 0,    unit: "",     item: "chili flakes", grp: "Stuffing" },
    ],
    steps: [
      { t: "Marinate the turkey overnight", d: "The night before, mix 5 minced garlic cloves, olive oil, Italian seasoning, extra rosemary/basil/thyme, salt, and pepper. Rub generously over the turkey. Cover and refrigerate overnight.", mins: 720, precision: "patient", hands: 0 },
      { t: "Prepare the stuffing",          d: "Cook the meat mixture in a large pan until browned. Combine with Stove Top stuffing, garlic, onions, Vegeta, pepper, eggs, basil, cranberries, and chili flakes. Mix thoroughly.", mins: 20, precision: "medium" },
      { t: "Stuff the turkey",              d: "Fill the turkey cavity with stuffing. Do not overpack — the stuffing expands as it cooks.", mins: 10, precision: "easy" },
      { t: "Start roasting",                d: "Preheat oven to 350°F. Place the turkey on a roasting rack and broil briefly for about 20 minutes to begin browning the skin.", mins: 20, precision: "watch" },
      { t: "Add the bacon and vegetables",  d: "Remove the turkey from the oven and layer thick-cut bacon across the top. Mix 1 more garlic clove with Italian seasoning and spread over the turkey. Add water to the bottom of the roasting pan along with potatoes, carrots, celery, neck, and giblets.", mins: 10, precision: "easy" },
      { t: "Roast and baste",               d: "Roast according to the turkey's weight, basting every 30 minutes. Done when the thickest part of the thigh reaches a safe internal temperature.", mins: 240, precision: "patient" },
      { t: "Rest before carving",           d: "Allow the turkey to rest at least 20–30 minutes before carving. Serve with stuffing, roasted vegetables, and pan drippings.", mins: 30, precision: "careful" },
    ],
    tips: [
      "Bacon protects the turkey while keeping everything rich, savory, and incredibly juicy.",
      "The vegetables underneath become intensely flavorful from the drippings — they're half the meal.",
      "Frequent basting is part of the ritual. Set a 30-minute timer.",
      "The overnight seasoning makes a huge difference. Don't skip it.",
      "Cranberries in the stuffing add little bursts of sweetness that balance the richness.",
      "Too much meat in the stuffing can prevent it from cooking through inside the turkey. Updated family rec: reduce the meat or go meatless. Always check temp by weight, not by time alone.",
    ],
    comments: [],
  },

  {
    id: "pierniki-gingerbread",
    title: "Gingerbread Ornaments (Traditional Pierniki)",
    subtitle: "Old Polish Christmas tradition — deeply spiced honey gingerbread. Firm at first, softer after days, even better with time.",
    author: "Traditional",
    cuisine: "Polish",
    course: "Dessert",
    diet: ["Vegetarian", "Dairy-free", "Nut-free"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&q=80",
    photoTone: "#6a3a18",
    favorite: false,
    rating: 4.8,
    cookCount: 3,
    servingsDefault: 35,
    prep: 45, cook: 11, total: 45 + 11 + 12 * 60, // includes overnight rest
    difficulty: "Patient",
    nutrition: { cal: 95, protein: 2, carbs: 18, fat: 1, fiber: 1, sodium: 35 },
    ingredients: [
      { qty: 1,    unit: "cup",  item: "honey, preferably dark or forest (340g)", grp: "Honey Base" },
      { qty: 0.25, unit: "cup",  item: "water (60ml)", grp: "Honey Base" },
      { qty: 2,    unit: "tbsp", item: "strong alcohol (vodka, rum, or brandy)", grp: "Honey Base" },
      { qty: 2,    unit: "tsp",  item: "ground ginger", grp: "Spices" },
      { qty: 2,    unit: "tsp",  item: "ground cinnamon", grp: "Spices" },
      { qty: 0.5,  unit: "tsp",  item: "ground cloves", grp: "Spices" },
      { qty: 0.5,  unit: "tsp",  item: "ground nutmeg", grp: "Spices" },
      { qty: 0.5,  unit: "tsp",  item: "ground cardamom", grp: "Spices" },
      { qty: 0.25, unit: "tsp",  item: "ground black pepper", grp: "Spices" },
      { qty: 0.25, unit: "tsp",  item: "ground anise or fennel", grp: "Spices" },
      { qty: 1,    unit: "",     item: "lemon, zested (lightly sautéed first, optional)", grp: "Spices" },
      { qty: 3,    unit: "tbsp", item: "sugar (2–4 to taste)", grp: "Sweetener" },
      { qty: 3.75, unit: "cups", item: "rye flour, 420–480g (start with less, add as needed)", grp: "Flour" },
      { qty: 0.5,  unit: "cup",  item: "beer (120ml)", grp: "For Brushing" },
      { qty: 2,    unit: "tbsp", item: "honey", grp: "For Brushing" },
    ],
    steps: [
      { t: "Heat the honey base", d: "In a saucepan, combine honey, water, and alcohol. Warm gently over low heat until smooth and slightly thickened. Skim off any foam so the honey becomes clear.", mins: 10, precision: "medium" },
      { t: "Add the spices",      d: "Stir in all spices, sugar, and lemon zest if using. Heat gently for another 2–3 minutes, stirring constantly. Do not boil aggressively.", mins: 3, precision: "easy" },
      { t: "Add the flour",       d: "Remove from heat and let cool slightly until warm but not hot. Gradually stir in the rye flour until a thick dough forms. Cover with a clean cloth and allow to cool completely.", mins: 15, precision: "medium" },
      { t: "Knead the dough",     d: "Transfer to a floured surface and knead firmly until smooth and workable. Add additional flour only as needed — the dough should stay soft but rollable.", mins: 10, precision: "patient" },
      { t: "Rest the dough",      d: "Wrap tightly and refrigerate overnight or up to 1 month for deeper flavor. Traditional piernik dough was often aged before baking.", mins: 720, precision: "patient", hands: 0 },
      { t: "Roll and cut",        d: "Roll dough to about ¼ inch (6 mm) thick. Cut into ornament or cookie shapes. If using as ornaments, poke a small hole near the top before baking.", mins: 15, precision: "easy" },
      { t: "Prepare the glaze",   d: "Simmer the beer and honey together for 2–3 minutes until combined. Brush lightly over the cookies before baking.", mins: 3, precision: "easy" },
      { t: "Bake",                d: "Bake at 350°F (175°C) for 10–12 minutes until just set. For softer cookies, slightly underbake.", mins: 11, precision: "watch" },
      { t: "Brush again",         d: "While still warm, brush lightly again with the beer-honey glaze if desired for shine and extra flavor. Cool completely before storing.", mins: 5, precision: "easy" },
    ],
    tips: [
      "Dark forest honey creates the richest flavor.",
      "Aging the dough develops complexity and improves texture — a week is great, a month is traditional.",
      "Rye flour gives traditional piernik its earthy depth.",
      "The beer-honey glaze creates a beautiful old-world shine.",
      "Stored in an airtight container, they last surprisingly well — and soften and deepen in flavor as they sit.",
    ],
    comments: [],
  },

  {
    id: "krystyna-apple-meringue-pie",
    title: "Krystyna's Apple Meringue Pie",
    subtitle: "Delicate layers of buttery crust, cinnamon apples, and cloud-like meringue. Old-world dessert that feels elegant without trying.",
    author: "Krystyna Fejdasz",
    cuisine: "Polish",
    course: "Dessert",
    diet: ["Vegetarian"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=1200&q=80",
    photoTone: "#a87838",
    favorite: false,
    rating: 5.0,
    cookCount: 4,
    servingsDefault: 11,
    prep: 60, cook: 55, total: 60 + 55 + 12 * 60, // includes overnight chill
    difficulty: "Patient",
    nutrition: { cal: 420, protein: 6, carbs: 46, fat: 24, fiber: 3, sodium: 180 },
    ingredients: [
      { qty: 1.8,  unit: "kg",   item: "Cortland apples, peeled and shredded", grp: "Apple Filling" },
      { qty: 0.25, unit: "cup",  item: "sugar (adjust to apple sweetness)", grp: "Apple Filling" },
      { qty: 0,    unit: "",     item: "cinnamon, to taste", grp: "Apple Filling" },
      { qty: 5,    unit: "",     item: "egg whites", grp: "Meringue" },
      { qty: 2,    unit: "tsp",  item: "potato flour or cornstarch", grp: "Meringue" },
      { qty: 1,    unit: "cup",  item: "sugar", grp: "Meringue" },
      { qty: 5,    unit: "",     item: "egg yolks (save whites for meringue)", grp: "Crust" },
      { qty: 3,    unit: "cups", item: "flour", grp: "Crust" },
      { qty: 250,  unit: "g",    item: "butter, semi-cold and cubed (1 cup)", grp: "Crust" },
      { qty: 1.5,  unit: "tsp",  item: "baking powder", grp: "Crust" },
      { qty: 0.5,  unit: "cup",  item: "sugar", grp: "Crust" },
      { qty: 1,    unit: "tbsp", item: "sugar (for crumble topping)", grp: "Crumble" },
      { qty: 1,    unit: "tbsp", item: "cold butter (for crumble topping)", grp: "Crumble" },
    ],
    steps: [
      { t: "Prepare the apples",      d: "Peel and shred the apples. Cook gently in a large pan with sugar and cinnamon until softened, but not fully broken down into mush. Cool completely.", mins: 22, precision: "medium" },
      { t: "Make the crust dough",    d: "Combine flour, sugar, baking powder, egg yolks, and cubed butter. Work the dough together quickly before the butter warms. Divide into two portions — a larger piece for the bottom crust, a smaller piece for the crumble topping. Wrap and freeze overnight. (You'll likely have enough for two pies.)", mins: 20, precision: "careful" },
      { t: "Chill overnight",         d: "Freeze the wrapped dough overnight. The freeze is what makes grating and crumbling easier later.", mins: 720, precision: "patient", hands: 0 },
      { t: "Prepare the meringue",    d: "Beat the egg whites until foamy. Add the potato flour or cornstarch, then slowly add sugar while continuing to beat until stiff glossy peaks form.", mins: 10, precision: "medium" },
      { t: "Bake the bottom crust",   d: "Preheat oven to 350°F (175°C). Grate or press the larger dough portion into the bottom of a baking dish or pie pan. Bake until lightly golden.", mins: 18, precision: "easy" },
      { t: "Assemble the pie",        d: "Spread the cooled apple filling over the baked crust. Top with the meringue. For the crumble: mix a small amount of reserved dough with 1 tbsp sugar and 1 tbsp cold butter. Crumble gently over the top.", mins: 10, precision: "easy" },
      { t: "Final bake",              d: "Return to the oven and bake until the meringue and crust are lightly golden. Cool before slicing.", mins: 30, precision: "watch" },
    ],
    tips: [
      "Cortland apples hold their texture beautifully — don't substitute a softer variety.",
      "Work quickly with cold butter to keep the crust tender.",
      "Slightly undercook the apples — they shouldn't be mushy or the filling becomes wet later.",
      "The pie slices best once fully cooled.",
      "Somehow tastes even better the next morning with coffee.",
    ],
    comments: [],
  },

  {
    id: "patricia-pumpkin-scones",
    title: "Patricia's Pumpkin Spice Scones",
    subtitle: "Adapted from Damn Delicious — soft, cozy pumpkin scones with warm fall spices and a double glaze. Starbucks nostalgia, homemade.",
    author: "Patricia",
    cuisine: "American",
    course: "Breakfast",
    diet: ["Vegetarian"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=1200&q=80",
    photoTone: "#b8722a",
    favorite: false,
    rating: 4.8,
    cookCount: 7,
    servingsDefault: 8,
    prep: 20, cook: 11, total: 45, // includes 10 min cool
    difficulty: "Easy",
    nutrition: { cal: 360, protein: 4, carbs: 48, fat: 17, fiber: 2, sodium: 240 },
    ingredients: [
      { qty: 2,    unit: "cups", item: "all-purpose flour", grp: "Scones" },
      { qty: 0.33, unit: "cup",  item: "brown sugar, packed", grp: "Scones" },
      { qty: 1,    unit: "tsp",  item: "cinnamon", grp: "Scones" },
      { qty: 1,    unit: "tsp",  item: "baking powder", grp: "Scones" },
      { qty: 0.75, unit: "tsp",  item: "ground cloves", grp: "Scones" },
      { qty: 0.5,  unit: "tsp",  item: "ground ginger", grp: "Scones" },
      { qty: 0.5,  unit: "tsp",  item: "ground nutmeg", grp: "Scones" },
      { qty: 0.5,  unit: "tsp",  item: "baking soda", grp: "Scones" },
      { qty: 0.25, unit: "tsp",  item: "salt", grp: "Scones" },
      { qty: 0.5,  unit: "cup",  item: "unsalted butter, cold and cubed (1 stick)", grp: "Scones" },
      { qty: 0.5,  unit: "cup",  item: "pumpkin puree", grp: "Scones" },
      { qty: 3,    unit: "tbsp", item: "milk", grp: "Scones" },
      { qty: 1,    unit: "",     item: "large egg", grp: "Scones" },
      { qty: 2,    unit: "tsp",  item: "vanilla extract", grp: "Scones" },
      { qty: 1,    unit: "cup",  item: "confectioners' sugar", grp: "Vanilla Glaze" },
      { qty: 2,    unit: "tbsp", item: "milk", grp: "Vanilla Glaze" },
      { qty: 1,    unit: "cup",  item: "confectioners' sugar", grp: "Spiced Glaze" },
      { qty: 0.25, unit: "tsp",  item: "cinnamon", grp: "Spiced Glaze" },
      { qty: 0.25, unit: "tsp",  item: "ground cloves", grp: "Spiced Glaze" },
      { qty: 0.25, unit: "tsp",  item: "ground ginger", grp: "Spiced Glaze" },
      { qty: 0,    unit: "pinch", item: "nutmeg", grp: "Spiced Glaze" },
      { qty: 2,    unit: "tbsp", item: "milk", grp: "Spiced Glaze" },
    ],
    steps: [
      { t: "Prep the oven",        d: "Preheat oven to 400°F. Line a baking sheet with parchment paper or a silicone baking mat.", mins: 5, precision: "easy" },
      { t: "Mix the dry ingredients", d: "Whisk together flour, brown sugar, cinnamon, baking powder, cloves, ginger, nutmeg, baking soda, and salt. Add the cold butter and work it in with your fingers or a pastry cutter until the mixture resembles coarse crumbs.", mins: 10, precision: "medium" },
      { t: "Mix the wet ingredients", d: "Whisk together pumpkin puree, milk, egg, and vanilla. Pour into the dry ingredients and stir gently until a soft dough forms.", mins: 5, precision: "easy" },
      { t: "Shape the dough",      d: "Turn dough onto a lightly floured surface. Knead gently 3–4 times. Roll into a rectangle about 10 × 7 inches, roughly 1 inch thick. Cut into 8 triangles.", mins: 10, precision: "easy" },
      { t: "Bake",                 d: "Transfer scones to the prepared baking sheet. Bake 10–12 minutes until lightly golden and cooked through. Cool 10 minutes before glazing.", mins: 11, precision: "watch" },
      { t: "Make the glazes",      d: "Vanilla glaze: whisk confectioners' sugar with milk until smooth. Spiced glaze: whisk confectioners' sugar with spices and milk until smooth. Add more milk if needed for desired consistency.", mins: 5, precision: "easy" },
      { t: "Glaze the scones",     d: "Spoon the vanilla glaze over slightly warm scones. Drizzle with the spiced glaze. Let the glazes set before serving.", mins: 5, precision: "easy" },
    ],
    tips: [
      "Cold butter is what creates the tender, flaky texture — keep it cold all the way to the oven.",
      "Don't overmix the dough — stop as soon as it comes together.",
      "Extra spice makes them taste more homemade and less overly sweet.",
      "The double glaze is non-negotiable.",
      "Best slightly warm with coffee. They make the apartment smell like autumn immediately.",
    ],
    comments: [],
  },

  {
    id: "patricia-tiramisu",
    title: "Tiramisu Treat",
    subtitle: "Creamy, fluffy, coffee-soaked. Mascarpone + Cool Whip keeps it light. Tastes even better straight from the fridge the next day.",
    author: "Patricia",
    cuisine: "Italian",
    course: "Dessert",
    diet: ["Vegetarian"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=1200&q=80",
    photoTone: "#5a3a28",
    favorite: false,
    rating: 4.9,
    cookCount: 8,
    servingsDefault: 11,
    prep: 40, cook: 0, total: 40 + 6 * 60, // includes 6 hr chill
    difficulty: "Easy",
    nutrition: { cal: 430, protein: 8, carbs: 33, fat: 28, fiber: 1, sodium: 120 },
    ingredients: [
      { qty: 2,    unit: "cups", item: "strong coffee or espresso (French press works beautifully)", grp: "Coffee Layer" },
      { qty: 0.25, unit: "cup",  item: "amaretto (or other coffee-friendly liqueur)", grp: "Coffee Layer" },
      { qty: 6,    unit: "",     item: "egg yolks", grp: "Cream Filling" },
      { qty: 0.75, unit: "cup",  item: "sugar", grp: "Cream Filling" },
      { qty: 16,   unit: "oz",   item: "mascarpone cheese", grp: "Cream Filling" },
      { qty: 1,    unit: "container", item: "Cool Whip", grp: "Cream Filling" },
      { qty: 4,    unit: "",     item: "egg whites", grp: "Cream Filling" },
      { qty: 2,    unit: "tbsp", item: "sugar", grp: "Cream Filling" },
      { qty: 2,    unit: "pkg",  item: "ladyfinger cookies (savoiardi)", grp: "Layers" },
      { qty: 0,    unit: "",     item: "cocoa powder, for dusting", grp: "Layers" },
    ],
    steps: [
      { t: "Prepare the coffee mixture", d: "Brew strong coffee or espresso and allow to cool. Stir in the amaretto. Set aside.", mins: 10, precision: "easy" },
      { t: "Make the mascarpone filling", d: "Whisk the egg yolks and sugar until pale, fluffy, and slightly thickened. Add mascarpone and mix until smooth. Fold in the Cool Whip until combined.", mins: 10, precision: "medium" },
      { t: "Whip the egg whites",        d: "In a separate clean bowl, beat the egg whites with 2 tbsp sugar until soft-to-medium peaks form. Gently fold the whipped whites into the mascarpone mixture last. Do not overmix — this keeps the filling light and airy.", mins: 10, precision: "careful" },
      { t: "Dip and layer",              d: "Quickly dip each ladyfinger into the coffee mixture — don't soak them too long or they'll become mushy. Arrange a layer in the bottom of a baking dish. Spread half the filling on top. Repeat with another layer of dipped ladyfingers and the remaining filling.", mins: 13, precision: "watch" },
      { t: "Chill",                      d: "Cover and refrigerate at least 6 hours, preferably overnight. The texture and flavor improve significantly after resting.", mins: 360, precision: "patient", hands: 0 },
      { t: "Finish and serve",           d: "Dust generously with cocoa powder just before serving. Serve chilled.", mins: 2, precision: "easy" },
    ],
    tips: [
      "Whipping the sugar into the yolks creates a silkier filling.",
      "Folding the whipped egg whites in last keeps everything airy. Don't deflate them.",
      "Amaretto adds warmth and depth without overpowering the coffee.",
      "French press coffee gives the richest homemade flavor.",
      "The hardest part is waiting overnight. Slightly messy slices usually taste the best.",
    ],
    comments: [],
  },
];

window.AUTHORS  = [...new Set(window.RECIPES.map(r => r.author))];
window.CUISINES = [...new Set(window.RECIPES.map(r => r.cuisine))];
window.COURSES  = ["Breakfast", "Lunch", "Dinner", "Appetizer", "Dessert", "Snack"];
window.DIETS    = ["Gluten-free","Dairy-free","Nut-free","Soy-free","Vegan","Vegetarian","Pescatarian","Carnivore","High protein","High fibre","Low carb","Low calorie"];
window.OCCASIONS = ["Solo","Family style","Date night"];
