// Family cookbook seed data.
window.RECIPES = [
  {
    id: "prime-rib",
    title: "Standing Prime Rib Roast",
    subtitle: "The 500° method. Set a timer, walk away — dinner is at 6.",
    author: "Dad",
    cuisine: "American",
    course: "Dinner",
    diet: ["Gluten-free", "High protein", "Low carb", "Carnivore"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=1200&q=80",
    photoTone: "#5a1818",
    favorite: true,
    rating: 4.9,
    cookCount: 12,
    // SPECIAL: scales by WEIGHT. Cook time = 5 min/lb at 500°F, then off-oven rest.
    scaleBy: "weight",
    weightDefault: 5.5,
    weightUnit: "lb",
    servingsDefault: 8,        // ~0.7 lb per person
    cookMinsPerLb: 5.09,       // 28 min for 5.5 lb
    prep: 15, cook: 28, total: 28 + 120 + 17 + 15,
    difficulty: "Easy",
    nutrition: { cal: 720, protein: 58, carbs: 0, fat: 54, fiber: 0, sodium: 620 },
    ingredients: [
      { qty: 5.5,  unit: "lb",   item: "standing prime rib roast, bone-in", grp: "Main", scalesWithWeight: true, perLb: 1 },
      { qty: 2,    unit: "tbsp", item: "kosher salt", grp: "Rub", scalesWithWeight: true, perLb: 0.36 },
      { qty: 1,    unit: "tbsp", item: "coarse black pepper", grp: "Rub", scalesWithWeight: true, perLb: 0.18 },
      { qty: 2,    unit: "tsp",  item: "garlic powder", grp: "Rub", scalesWithWeight: true, perLb: 0.36 },
      { qty: 2,    unit: "tbsp", item: "fresh rosemary + thyme, chopped", grp: "Rub", scalesWithWeight: true, perLb: 0.36 },
      { qty: 4,    unit: "tbsp", item: "softened butter (optional herb-butter slather)", grp: "Rub", scalesWithWeight: true, perLb: 0.73 },
      { qty: 0,    unit: "",     item: "Horseradish cream or au jus, to serve", grp: "Serve" },
    ],
    steps: [
      { t: "Take roast out of fridge", d: "Sit on the counter uncovered (or loosely tented with parchment). 2½ hours minimum — even cooking depends on it.",                mins: 0,   precision: "easy",    label: "rest-pre" },
      { t: "Preheat oven",             d: "500°F. Rack in the lower-middle position.",                                                                                       mins: 15,  precision: "easy" },
      { t: "Season the roast",         d: "Pat dry. Rub with the salt-pepper-garlic-herb mix all over. Optional herb butter slather.",                                       mins: 10,  precision: "medium" },
      { t: "Roast at 500°F",           d: "Uncovered, fat-cap up. Timer for {COOKMINS} minutes.",                                                                            mins: 28,  precision: "watch",   dynamic: "cook" },
      { t: "Turn oven OFF",            d: "Do NOT open the door. The residual heat finishes the roast. 2 hr = medium-rare (130–135°F). 2¼ hr = medium (135–140°F).",          mins: 120, precision: "patient" },
      { t: "Pull and check",           d: "Check internal temp. 130°F for medium-rare. The crust will be deep mahogany.",                                                    mins: 2,   precision: "careful" },
      { t: "Rest",                     d: "Tent loosely with foil. 15 minutes — non-negotiable.",                                                                            mins: 17,  precision: "easy" },
      { t: "Slice and serve",          d: "Carve along the bones, then slice across the grain. Horseradish cream or au jus alongside.",                                      mins: 10,  precision: "medium" },
    ],
    tips: [
      "Cook time scales at ~5 minutes per pound at 500°F. The 'off oven' rest stays at 2 hours regardless.",
      "Pull the roast from the fridge 2½ hours before searing. Cold-center beef cooks unevenly.",
      "Do not open the oven during the off-oven phase. You will undo the entire method.",
    ],
    comments: [
      { name: "Mom", date: "Dec 25", text: "Did this Christmas for 14 people with an 8 lb roast — 41 minutes hot, 2 hours off. Perfect edge to edge." },
      { name: "Pete", date: "Nov 12", text: "Saved $40 buying the whole rib and tying it myself. Same result." },
    ],
  },

  {
    id: "linguine-vongole",
    title: "Linguine alle Vongole",
    subtitle: "Pantry-friendly. White wine, garlic, clams — done in 15 minutes.",
    author: "Mom",
    cuisine: "Italian",
    course: "Dinner",
    diet: ["Dairy-free option", "Pescatarian", "High protein"],
    occasion: "Date night",
    photo: "https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=1200&q=80",
    photoTone: "#3a5a3a",
    favorite: true,
    rating: 4.8,
    cookCount: 26,
    servingsDefault: 4,
    prep: 5, cook: 15, total: 20,
    difficulty: "Easy",
    nutrition: { cal: 540, protein: 22, carbs: 64, fat: 19, fiber: 3, sodium: 720 },
    ingredients: [
      { qty: 1,    unit: "pkg",   item: "linguini (about 1 lb)", grp: "Pasta" },
      { qty: 0.25, unit: "cup",   item: "olive oil (plus more to finish)", grp: "Pasta" },
      { qty: 2,    unit: "tbsp",  item: "unsalted butter", grp: "Pasta" },
      { qty: 2,    unit: "tbsp",  item: "pre-minced garlic (or 3–6 fresh cloves, minced)", grp: "Pasta" },
      { qty: 1,    unit: "tbsp",  item: "red pepper flakes", grp: "Pasta" },
      { qty: 8,    unit: "oz",    item: "clam juice (1 bottle)", grp: "Clams" },
      { qty: 2,    unit: "cans",  item: "minced/chopped clams, with juice", grp: "Clams" },
      { qty: 0.5,  unit: "cup",   item: "white wine (Chardonnay or Pinot Grigio)", grp: "Clams" },
      { qty: 0.5,  unit: "",      item: "lemon, zested (optional)", grp: "Finish" },
      { qty: 3,    unit: "tbsp",  item: "Parmesan, finely grated (optional)", grp: "Finish" },
      { qty: 1,    unit: "bunch", item: "fresh parsley, chopped", grp: "Finish" },
      { qty: 0,    unit: "",      item: "salt and pepper, to taste", grp: "Finish" },
    ],
    steps: [
      { t: "Boil the pasta",      d: "Heavily salted water — like the sea. Cook linguini just shy of al dente. Reserve a cup of pasta water before draining.", mins: 9, precision: "medium" },
      { t: "Bloom the aromatics", d: "Olive oil in a large pan, medium. Garlic + red pepper flakes — cook 1–2 minutes until fragrant. Don't brown the garlic.", mins: 2, precision: "watch" },
      { t: "Wine + clam juice",   d: "Add clam juice and white wine. Simmer 2–3 minutes to take the alcohol edge off.",                                          mins: 3, precision: "easy" },
      { t: "Add the clams",       d: "Stir in canned clams with their juice. Simmer another 2–3 minutes.",                                                       mins: 3, precision: "easy" },
      { t: "Season",              d: "Lemon zest (if using), salt, plenty of black pepper.",                                                                     mins: 1, precision: "easy" },
      { t: "Toss",                d: "Drained pasta into the sauce with a splash of pasta water. Toss vigorously until glossy.",                                 mins: 2, precision: "medium" },
      { t: "Finish off heat",     d: "Off the heat: butter and Parm. Stir to emulsify. Parsley on top. Serve immediately.",                                      mins: 1, precision: "careful" },
    ],
    tips: [
      "Replace 1 can with fresh vongole clams if you can find them — steam them open in the sauce.",
      "Want a thicker sauce? Whisk 1 tbsp of flour into the wine before adding.",
      "Reserved pasta water is the secret. Add it a splash at a time until the sauce coats the strands.",
    ],
    comments: [
      { name: "Jules", date: "May 14", text: "Date-night go-to. Open the second bottle of wine when the first one hits the pan." },
    ],
  },

  {
    id: "blueberry-lemon-rolls",
    title: "Blueberry Lemon Pie Rolls",
    subtitle: "Cinnamon roll meets blueberry pie. Lemon glaze on top.",
    author: "Aunt Rosa",
    cuisine: "American",
    course: "Breakfast",
    diet: ["Vegetarian"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=1200&q=80",
    photoTone: "#5a3a7a",
    favorite: false,
    rating: 4.7,
    cookCount: 7,
    servingsDefault: 9,
    prep: 30, cook: 30, total: 60 + 60, // includes rise
    difficulty: "Medium",
    nutrition: { cal: 380, protein: 6, carbs: 62, fat: 12, fiber: 2, sodium: 280 },
    ingredients: [
      { qty: 3.25, unit: "cups", item: "all-purpose flour", grp: "Dough" },
      { qty: 0.25, unit: "cup",  item: "sugar", grp: "Dough" },
      { qty: 2.25, unit: "tsp",  item: "instant yeast (1 packet)", grp: "Dough" },
      { qty: 0.75, unit: "tsp",  item: "kosher salt", grp: "Dough" },
      { qty: 0.75, unit: "cup",  item: "warm whole milk", grp: "Dough" },
      { qty: 4,    unit: "tbsp", item: "butter, melted and slightly cooled", grp: "Dough" },
      { qty: 1,    unit: "",     item: "large egg", grp: "Dough" },
      { qty: 1,    unit: "tsp",  item: "vanilla", grp: "Dough" },
      { qty: 2,    unit: "cups", item: "blueberries (fresh or frozen, don't thaw)", grp: "Filling" },
      { qty: 0.33, unit: "cup",  item: "sugar", grp: "Filling" },
      { qty: 2,    unit: "tbsp", item: "cornstarch", grp: "Filling" },
      { qty: 1,    unit: "",     item: "lemon, zested and juiced", grp: "Filling" },
      { qty: 1,    unit: "cup",  item: "powdered sugar", grp: "Glaze" },
      { qty: 2,    unit: "tbsp", item: "lemon juice", grp: "Glaze" },
      { qty: 1,    unit: "tsp",  item: "lemon zest", grp: "Glaze" },
    ],
    steps: [
      { t: "Activate the yeast",  d: "Warm milk (105°F) + sugar + yeast. Sit 5 minutes until foamy.", mins: 5, precision: "medium" },
      { t: "Mix the dough",       d: "Add melted butter, egg, vanilla. Stir in flour + salt until shaggy. Knead 6–8 minutes until smooth and elastic.", mins: 12, precision: "medium" },
      { t: "First rise",          d: "Oiled bowl, covered. Warm spot. 1 hour, until doubled.", mins: 60, precision: "easy", hands: 0 },
      { t: "Make the filling",    d: "Toss blueberries with sugar, cornstarch, lemon zest, lemon juice. Don't pre-cook — they jam inside the rolls.", mins: 3, precision: "easy" },
      { t: "Roll and fill",       d: "Punch down. Roll dough into a 12×16 rectangle. Spread blueberry filling, leaving a 1\" border.", mins: 8, precision: "careful" },
      { t: "Roll and slice",      d: "Roll up tightly from the long side. Slice with unflavored dental floss into 9 rolls. Floss beats a knife — no smushing.", mins: 5, precision: "careful" },
      { t: "Second rise",         d: "Rolls in a buttered 9×13. Cover. 30–40 minutes until puffy and touching.", mins: 35, precision: "easy", hands: 0 },
      { t: "Bake",                d: "375°F until tops are deeply golden and the centers are set.", mins: 28, precision: "watch" },
      { t: "Glaze warm",          d: "Whisk powdered sugar + lemon juice + zest. Pour over rolls while still warm. Eat one before anyone notices.", mins: 4, precision: "easy" },
    ],
    tips: [
      "Frozen blueberries: do not thaw. They bleed less, and the cold helps the dough hold its shape during slicing.",
      "Make-ahead: shape the rolls, cover, and refrigerate overnight after step 6. Let them warm up 30 min before baking.",
      "Want them extra rich? Brush the rolled dough with 2 tbsp soft butter before adding the filling.",
    ],
    comments: [
      { name: "Sam", date: "Jul 4", text: "Brought to brunch — gone in 4 minutes. The dental floss trick is real." },
      { name: "Em",  date: "Jun 20", text: "Did half blueberry, half raspberry. Worth it." },
    ],
  },

  {
    id: "nonnas-lasagna",
    title: "Nonna's Sunday Lasagna",
    subtitle: "Six hours of sauce, twelve layers, one family.",
    author: "Nonna Lucia",
    cuisine: "Italian",
    course: "Dinner",
    diet: ["Vegetarian-friendly"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=1200&q=80",
    photoTone: "#7a2e1f",
    favorite: true,
    rating: 4.9,
    cookCount: 47,
    servingsDefault: 8,
    prep: 60, cook: 240, total: 300,
    difficulty: "Patient",
    nutrition: { cal: 612, protein: 34, carbs: 48, fat: 31, fiber: 5, sodium: 740 },
    ingredients: [
      { qty: 2,    unit: "lb",    item: "ground beef chuck (80/20)", grp: "Sauce" },
      { qty: 1,    unit: "lb",    item: "sweet Italian sausage, casings off", grp: "Sauce" },
      { qty: 2,    unit: "",      item: "yellow onions, finely diced", grp: "Sauce" },
      { qty: 6,    unit: "",      item: "garlic cloves, minced", grp: "Sauce" },
      { qty: 2,    unit: "28oz",  item: "cans San Marzano tomatoes, crushed by hand", grp: "Sauce" },
      { qty: 1,    unit: "cup",   item: "dry red wine", grp: "Sauce" },
      { qty: 2,    unit: "tbsp",  item: "tomato paste", grp: "Sauce" },
      { qty: 1,    unit: "tsp",   item: "dried oregano", grp: "Sauce" },
      { qty: 1,    unit: "bunch", item: "fresh basil, torn", grp: "Sauce" },
      { qty: 1,    unit: "lb",    item: "fresh lasagna sheets", grp: "Pasta" },
      { qty: 32,   unit: "oz",    item: "whole-milk ricotta", grp: "Cheese" },
      { qty: 1,    unit: "lb",    item: "fresh mozzarella, torn", grp: "Cheese" },
      { qty: 2,    unit: "cups",  item: "Parmigiano-Reggiano, grated", grp: "Cheese" },
      { qty: 2,    unit: "",      item: "eggs, beaten", grp: "Cheese" },
      { qty: 0.25, unit: "cup",   item: "flat-leaf parsley, chopped", grp: "Cheese" },
    ],
    steps: [
      { t: "Sweat the soffritto",  d: "Warm olive oil over medium-low. Cook onions 12 min until translucent. Add garlic, cook 2 min more.", mins: 15, precision: "easy" },
      { t: "Brown the meat",        d: "Push aromatics aside. Add beef and sausage in batches; brown deeply — don't crowd the pan.", mins: 20, precision: "medium" },
      { t: "Deglaze",               d: "Wine in, scrape the fond. Reduce by half.", mins: 8, precision: "easy" },
      { t: "Build the sauce",       d: "Tomato paste; toast 2 min. Crushed tomatoes, oregano, salt. Bring to a bare simmer.", mins: 10, precision: "easy" },
      { t: "Simmer low and slow",   d: "Partially covered. Stir every 30 min. Ready when a spoon leaves a clean trail.", mins: 180, precision: "patient", hands: 10 },
      { t: "Mix the cheese",        d: "Whisk ricotta, eggs, half the Parm, parsley, ½ tsp salt, pepper.", mins: 5, precision: "easy" },
      { t: "Layer",                 d: "Sauce → pasta → ricotta → mozzarella → Parm. Repeat 4× — ending with sauce + mozz on top.", mins: 20, precision: "careful" },
      { t: "Bake covered",          d: "375°F, foil on. Pull when bubbling at the edges.", mins: 35, precision: "easy" },
      { t: "Bake uncovered",        d: "Foil off. Until top is blistered and deeply golden.", mins: 15, precision: "watch" },
      { t: "Rest",                  d: "Hardest step. 20 minutes minimum, or it slumps on the plate.", mins: 20, precision: "easy" },
    ],
    tips: [
      "Nonna swears by hand-crushing the tomatoes — 'the machine bruises them.'",
      "If the sauce tightens up, splash in pasta water, never plain water.",
      "Day-old lasagna is better. Cut cold, reheat covered at 325°F.",
    ],
    comments: [
      { name: "Marco", date: "Mar 2",  text: "Made this for Easter. My mother-in-law asked for the recipe. From a Sicilian woman. I have arrived." },
      { name: "Elena", date: "Feb 18", text: "Used venison instead of beef — incredible. The long simmer carries it." },
    ],
  },

  {
    id: "grandma-biscuits",
    title: "Grandma's Buttermilk Biscuits",
    subtitle: "Cold butter, warm hands, soft touch.",
    author: "Grandma June",
    cuisine: "Southern",
    course: "Breakfast",
    diet: ["Vegetarian"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1568051243851-f9b136146e97?w=1200&q=80",
    photoTone: "#8a6a3a",
    favorite: true,
    rating: 4.8,
    cookCount: 89,
    servingsDefault: 12,
    prep: 15, cook: 18, total: 33,
    difficulty: "Easy",
    nutrition: { cal: 218, protein: 4, carbs: 25, fat: 11, fiber: 1, sodium: 380 },
    ingredients: [
      { qty: 3,   unit: "cups", item: "all-purpose flour", grp: "Dry" },
      { qty: 1,   unit: "tbsp", item: "baking powder", grp: "Dry" },
      { qty: 0.5, unit: "tsp",  item: "baking soda", grp: "Dry" },
      { qty: 1,   unit: "tsp",  item: "kosher salt", grp: "Dry" },
      { qty: 1,   unit: "tbsp", item: "sugar", grp: "Dry" },
      { qty: 12,  unit: "tbsp", item: "very cold unsalted butter, cubed", grp: "Fat" },
      { qty: 1.25,unit: "cups", item: "cold buttermilk, plus more for brushing", grp: "Wet" },
    ],
    steps: [
      { t: "Freeze the butter", d: "Cube it. Freeze 15 minutes. Non-negotiable.", mins: 15, precision: "easy" },
      { t: "Whisk dry",         d: "Flour, powder, soda, salt, sugar — combined.", mins: 2, precision: "easy" },
      { t: "Cut in butter",     d: "Pastry cutter or fingertips. Pea-sized lumps. STOP early.", mins: 4, precision: "careful" },
      { t: "Add buttermilk",    d: "Pour around the edges. Fold 6 times. Shaggy is correct.", mins: 2, precision: "careful" },
      { t: "Laminate",          d: "Pat into a rectangle. Fold in thirds. Repeat 3×. This is your layers.", mins: 5, precision: "medium" },
      { t: "Cut",                d: "Pat to 1 inch. Cut straight down — never twist. Twisting seals the layers.", mins: 3, precision: "careful" },
      { t: "Bake",               d: "450°F, biscuits touching, brushed with buttermilk. Until golden and tall.", mins: 18, precision: "watch" },
    ],
    tips: [
      "If your kitchen is warm, chill the bowl too.",
      "Re-rolling once is okay; twice and they'll be tough.",
    ],
    comments: [
      { name: "Annie", date: "May 3",  text: "These ruined every other biscuit for me." },
      { name: "Tom",   date: "Mar 22", text: "Added 1 cup sharp cheddar + scallions. Grandma would forgive me." },
    ],
  },

  {
    id: "dads-chili",
    title: "Dad's Smoky Chili",
    subtitle: "No beans. He'll die on this hill.",
    author: "Dad",
    cuisine: "Tex-Mex",
    course: "Dinner",
    diet: ["Gluten-free", "High protein", "Low carb"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1547308283-b941a3a82bd2?w=1200&q=80",
    photoTone: "#5a1f12",
    favorite: false,
    rating: 4.7,
    cookCount: 31,
    servingsDefault: 6,
    prep: 25, cook: 150, total: 175,
    difficulty: "Easy",
    nutrition: { cal: 528, protein: 41, carbs: 12, fat: 34, fiber: 4, sodium: 690 },
    ingredients: [
      { qty: 3, unit: "lb",   item: "beef chuck, cut into ½-inch cubes", grp: "Meat" },
      { qty: 4, unit: "",     item: "dried ancho chiles, stemmed and seeded", grp: "Chiles" },
      { qty: 2, unit: "",     item: "dried guajillo chiles", grp: "Chiles" },
      { qty: 2, unit: "",     item: "chipotles in adobo, chopped", grp: "Chiles" },
      { qty: 1, unit: "tbsp", item: "smoked paprika", grp: "Chiles" },
      { qty: 1, unit: "tbsp", item: "ground cumin, toasted", grp: "Chiles" },
      { qty: 1, unit: "",     item: "large yellow onion, diced", grp: "Aromatics" },
      { qty: 6, unit: "",     item: "garlic cloves", grp: "Aromatics" },
      { qty: 2, unit: "cups", item: "beef stock", grp: "Liquid" },
      { qty: 1, unit: "bottle", item: "dark Mexican lager", grp: "Liquid" },
      { qty: 2, unit: "tbsp", item: "masa harina (to thicken)", grp: "Finish" },
      { qty: 1, unit: "oz",   item: "dark chocolate, chopped", grp: "Finish" },
    ],
    steps: [
      { t: "Toast the chiles",      d: "Dry skillet, medium-high. 30 sec/side until fragrant — do not burn.", mins: 5, precision: "watch" },
      { t: "Soak",                  d: "Cover with boiling water. Steep 15 minutes.", mins: 15, precision: "easy" },
      { t: "Sear the beef",         d: "Cast iron, ripping hot. Sear in batches. Don't move them.", mins: 20, precision: "medium" },
      { t: "Blend the chile paste", d: "Drained chiles + soaking water + garlic + chipotles. Smooth.", mins: 5, precision: "easy" },
      { t: "Build the base",        d: "Sweat onion. Chile paste + cumin + paprika. 3 minutes.", mins: 8, precision: "easy" },
      { t: "Braise",                d: "Beef back in, stock + beer to cover. Lid askew. 275°F.", mins: 120, precision: "patient", hands: 5 },
      { t: "Tighten",               d: "Whisk masa into cold water. Stir in. Add chocolate. 10 more minutes.", mins: 10, precision: "easy" },
    ],
    tips: ["No tomato. No beans. This is chili con carne, not stew.", "Toast cumin whole, then grind — it's a different spice."],
    comments: [{ name: "Sam", date: "Apr 8", text: "Added a tbsp of coffee with the stock. Don't tell Dad." }],
  },

  {
    id: "sunday-roast-chicken",
    title: "Mom's Sunday Roast Chicken",
    subtitle: "The bird that taught us how to cook.",
    author: "Mom",
    cuisine: "American",
    course: "Dinner",
    diet: ["Gluten-free", "High protein", "Carnivore"],
    occasion: "Family style",
    photo: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=1200&q=80",
    photoTone: "#7a5024",
    favorite: true,
    rating: 4.9,
    cookCount: 64,
    servingsDefault: 4,
    prep: 20, cook: 70, total: 90,
    difficulty: "Easy",
    nutrition: { cal: 480, protein: 52, carbs: 6, fat: 28, fiber: 1, sodium: 540 },
    ingredients: [
      { qty: 1,   unit: "",     item: "whole chicken, 4–5 lb, patted dry", grp: "Main" },
      { qty: 1,   unit: "",     item: "lemon, halved", grp: "Main" },
      { qty: 1,   unit: "head", item: "garlic, halved crosswise", grp: "Main" },
      { qty: 1,   unit: "bunch",item: "thyme", grp: "Main" },
      { qty: 4,   unit: "tbsp", item: "butter, softened", grp: "Main" },
      { qty: 1.5, unit: "lb",   item: "small Yukon gold potatoes, halved", grp: "Veg" },
      { qty: 2,   unit: "",     item: "shallots, quartered", grp: "Veg" },
      { qty: 2,   unit: "tbsp", item: "olive oil", grp: "Veg" },
    ],
    steps: [
      { t: "Salt the bird (overnight if you can)", d: "1 tsp kosher salt per pound. Uncovered in the fridge = shatter-crisp skin.", mins: 5,  precision: "easy" },
      { t: "Heat oven",         d: "425°F. Rack in the lower third.",                                                  mins: 10, precision: "easy" },
      { t: "Stuff & truss",     d: "Lemon, garlic, thyme in the cavity. Tie the legs. Butter under the skin.",         mins: 8,  precision: "medium" },
      { t: "Bed of vegetables", d: "Toss potatoes + shallots in oil, salt. Spread in roasting pan.",                   mins: 5,  precision: "easy" },
      { t: "Roast",             d: "Chicken on top. 70 min, until thigh reads 165°F. Baste once at 40 min.",            mins: 70, precision: "easy" },
      { t: "Rest",              d: "Tent loosely. 15 minutes.",                                                         mins: 15, precision: "easy" },
      { t: "Carve",             d: "Legs first, then breasts off the bone. Save the carcass for stock.",                mins: 5,  precision: "medium" },
    ],
    tips: ["Dry skin = crisp skin. Pat until your towel is wet.", "If you skip the overnight salt, salt 1 hour before roasting at least."],
    comments: [{ name: "Em", date: "Apr 28", text: "I make this every other Sunday. Stock fridge is always full." }],
  },

  {
    id: "scallion-pancakes",
    title: "Cousin Mei's Scallion Pancakes",
    subtitle: "Cong you bing. Worth every fold.",
    author: "Cousin Mei",
    cuisine: "Chinese",
    course: "Appetizer",
    diet: ["Vegan"],
    occasion: "Solo",
    photo: "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=1200&q=80",
    photoTone: "#8a6a2a",
    favorite: false,
    rating: 4.7,
    cookCount: 18,
    servingsDefault: 4,
    prep: 40, cook: 20, total: 60,
    difficulty: "Medium",
    nutrition: { cal: 310, protein: 6, carbs: 38, fat: 14, fiber: 2, sodium: 420 },
    ingredients: [
      { qty: 2,    unit: "cups", item: "all-purpose flour", grp: "Dough" },
      { qty: 0.75, unit: "cup",  item: "boiling water", grp: "Dough" },
      { qty: 0.25, unit: "cup",  item: "cold water", grp: "Dough" },
      { qty: 1,    unit: "tsp",  item: "salt", grp: "Dough" },
      { qty: 1,    unit: "bunch",item: "scallions, thinly sliced", grp: "Filling" },
      { qty: 3,    unit: "tbsp", item: "toasted sesame oil", grp: "Filling" },
    ],
    steps: [
      { t: "Make the dough", d: "Pour boiling water into flour while stirring, then cold water. Knead 5 min until smooth.", mins: 10, precision: "medium" },
      { t: "Rest",           d: "Cover. 30 minutes minimum.", mins: 30, precision: "easy" },
      { t: "Roll and brush", d: "Divide into 4. Roll thin oval. Brush with sesame oil, scatter scallions and salt.", mins: 8, precision: "careful" },
      { t: "Roll and coil",  d: "Roll into a log. Coil into a spiral. Press flat. Re-roll into a pancake.", mins: 6, precision: "careful" },
      { t: "Fry",            d: "Neutral oil, medium-high. 3 min/side until crispy.", mins: 12, precision: "medium" },
    ],
    tips: ["Boiling water gives you a tender pancake. Don't skip it.", "Serve with soy + black vinegar + chili crisp."],
    comments: [{ name: "Jay", date: "Mar 11", text: "The spiral is the magic. Don't half-ass it." }],
  },

  {
    id: "olive-oil-cake",
    title: "Aunt Rosa's Lemon Olive Oil Cake",
    subtitle: "Three ingredients you actually have. Tastes like sunshine.",
    author: "Aunt Rosa",
    cuisine: "Italian",
    course: "Dessert",
    diet: ["Vegetarian"],
    occasion: "Solo",
    photo: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=1200&q=80",
    photoTone: "#c08a3a",
    favorite: false,
    rating: 4.6,
    cookCount: 22,
    servingsDefault: 10,
    prep: 15, cook: 45, total: 60,
    difficulty: "Easy",
    nutrition: { cal: 340, protein: 5, carbs: 38, fat: 19, fiber: 1, sodium: 180 },
    ingredients: [
      { qty: 1.75, unit: "cups", item: "all-purpose flour", grp: "Dry" },
      { qty: 1,    unit: "cup",  item: "sugar", grp: "Dry" },
      { qty: 1.5,  unit: "tsp",  item: "baking powder", grp: "Dry" },
      { qty: 0.5,  unit: "tsp",  item: "kosher salt", grp: "Dry" },
      { qty: 3,    unit: "",     item: "large eggs", grp: "Wet" },
      { qty: 0.75, unit: "cup",  item: "extra-virgin olive oil (a good one)", grp: "Wet" },
      { qty: 0.75, unit: "cup",  item: "whole milk (or oat milk)", grp: "Wet" },
      { qty: 2,    unit: "",     item: "lemons, zested and juiced", grp: "Wet" },
    ],
    steps: [
      { t: "Heat oven",   d: "350°F. Grease and line a 9-inch round.", mins: 5,  precision: "easy" },
      { t: "Whisk wet",   d: "Eggs + sugar 2 min until pale. Stream in oil. Add milk, juice, zest.", mins: 5,  precision: "easy" },
      { t: "Fold in dry", d: "Sift dry over. Fold just until combined. Don't overmix.", mins: 3,  precision: "careful" },
      { t: "Bake",        d: "Until a skewer comes out with a few moist crumbs.", mins: 45, precision: "easy" },
      { t: "Cool",        d: "In pan 15 min, then on a rack. Dust with powdered sugar.", mins: 30, precision: "easy" },
    ],
    tips: ["Use an olive oil you'd eat off a spoon — it's the flavor.", "A splash of limoncello in the batter is allowed."],
    comments: [{ name: "Lucy", date: "Feb 14", text: "Made it with blood oranges in winter. Stunning." }],
  },
];

window.AUTHORS  = [...new Set(window.RECIPES.map(r => r.author))];
window.CUISINES = [...new Set(window.RECIPES.map(r => r.cuisine))];
window.COURSES  = ["Breakfast", "Lunch", "Dinner", "Appetizer", "Dessert", "Snack"];
window.DIETS    = ["Gluten-free","Dairy-free","Nut-free","Soy-free","Vegan","Vegetarian","Pescatarian","Carnivore","High protein","High fibre","Low carb","Low calorie"];
window.OCCASIONS = ["Solo","Family style","Date night"];
