// One-off: read src/data.js and emit migrations/0002_seed_recipes.sql.
// Re-run only if the seed data in src/data.js changes; otherwise this file
// has done its job and the SQL it produced is what matters.

import { writeFileSync } from "fs";
import { RECIPES } from "../src/data.js";

const sqlEscape = (v) => v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const now = Date.now();

const lines = [
  "-- Seed: 14 recipes from src/data.js. Generated by scripts/gen-seed.mjs.",
  "-- Apply this AFTER 0001_initial_schema.sql.",
  "",
];

for (const r of RECIPES) {
  const blob = JSON.stringify(r);
  lines.push(
    `INSERT INTO recipes (id, title, subtitle, author, cuisine, course, photo, blob, created_at, updated_at)`,
    `VALUES (${sqlEscape(r.id)}, ${sqlEscape(r.title)}, ${sqlEscape(r.subtitle)}, ${sqlEscape(r.author)}, ${sqlEscape(r.cuisine)}, ${sqlEscape(r.course)}, ${sqlEscape(r.photo)}, ${sqlEscape(blob)}, ${now}, ${now});`,
    "",
  );
}

writeFileSync(new URL("../migrations/0002_seed_recipes.sql", import.meta.url), lines.join("\n"));
console.log(`Wrote ${RECIPES.length} recipes to migrations/0002_seed_recipes.sql`);
